services:
  postgres:
    image: postgres
    container_name: pay-your-dues-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pay_your_dues
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pay-your-dues-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pay-your-dues-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pay-your-dues-network

  localstack:
    image: localstack/localstack:latest
    container_name: pay-your-dues-localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
    env_file:
      - .env
    volumes:
      - localstack_data:/var/lib/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init_s3.py:/etc/localstack/init/ready.d/init_s3.py
    networks:
      - pay-your-dues-network

volumes:
  postgres_data:
    driver: local
  localstack_data:
    driver: local

networks:
  pay-your-dues-network:
    driver: bridge
